### ISSUE TITLE
Duplicate user show in Video conference 

### ISSUE THREAD

**Issue by SameerkhanQs** [ZEGOCLOUD/zego_uikit_prebuilt_video_conference_flutter#1]
when one user leaves and then joins again join then shows duplicate users 
![MicrosoftTeams-image (1)](https://github.com/ZEGOCLOUD/zego_uikit_prebuilt_video_conference_flutter/assets/140138698/76e365eb-acd2-4355-b56d-fc185795e5fe)
![MicrosoftTeams-image (2)](https://github.com/ZEGOCLOUD/zego_uikit_prebuilt_video_conference_flutter/assets/140138698/9103d135-0af2-4c13-8be9-5d1613005066)

**Comment by yoer** [comment]
During the past period, I have been busy with other projects. Now, let me take a look

**Comment by yoer** [comment]
I ran our [demo](https://github.com/ZEGOCLOUD/zego_uikit_prebuilt_video_conference_example_flutter/tree/master/video_conference) and didn't reproduce this issue. Can you send me the code you integrated so I can take a look?
