### ISSUE TITLE
How I can do pip with zego_uikit_prebuilt_video_conference_flutter

### ISSUE THREAD

**Issue by Tareq850** [ZEGOCLOUD/zego_uikit_prebuilt_video_conference_flutter#2]
In fact, I looked at all the files, and I did not find a way to activate the picture-in-picture feature, so that when sharing the screen, the user can minimize the meeting screen in order to open other pages and applications

**Comment by yoer** [comment]
I'm sorry, but we currently do not support system-level PIP layout.
